# Generated by Django 5.2.10 on 2026-02-08 07:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_org', '0001_initial'),
        ('staffing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uwi', models.CharField(max_length=50, unique=True, verbose_name='Unique Well Identifier')),
                ('well_name', models.CharField(max_length=100)),
                ('field_name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_org.asset')),
            ],
        ),
        migrations.CreateModel(
            name='WellProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_type', models.CharField(choices=[('EXPLORE', 'Exploration'), ('DRILL', 'Drilling'), ('COMPLETE', 'Completion'), ('PROD', 'Production'), ('ABANDON', 'Abandoned')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'in Review/Approval'), ('APPROVED', 'Approved/Active'), ('ON_HOLD', 'On Hold'), ('CLOSED', 'Completed/Closed')], default='DRAFT', max_length=20)),
                ('current_stage', models.CharField(choices=[('EXPLORE', 'Exploration'), ('DRILL', 'Drilling'), ('COMPLETE', 'Completion'), ('PROD', 'Production'), ('ABANDON', 'Abandoned')], default='EXPLORATION', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(help_text='The date by which current approval step is due')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('assigned_to_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_projects', to='staffing.position')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='well_assets.well')),
            ],
        ),
    ]
