# Generated by Django 5.2.10 on 2026-02-08 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('NORTH', 'North Asset'), ('SOUTH', 'South Asset'), ('EAST', 'East Asset')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrgUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit_type', models.CharField(choices=[('CORP', 'Corporate/Executive'), ('DEPT', 'Department'), ('DIV', 'Division'), ('GROUP', 'Group/Unit')], max_length=10)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_units', to='core_org.orgunit')),
            ],
        ),
    ]
