# Generated by Django 5.2.10 on 2026-02-08 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('rank_level', models.IntegerField(choices=[(10, 'Executive (Sr.VP / VP)'), (8, 'Director'), (6, 'Manager'), (4, 'Supervisor/Lead'), (2, 'Technical/Staff')])),
                ('is_unit_head', models.BooleanField(default=False)),
                ('org_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core_org.orgunit')),
                ('reports_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffing.position')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delegate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffing.employee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staffing.position')),
            ],
        ),
    ]
