# Generated by Django 5.2.10 on 2026-02-08 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staffing', '0001_initial'),
        ('well_assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='well_assets.wellproject')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('EXPLORE', 'Exploration'), ('DRILL', 'Drilling'), ('COMPLETE', 'Completion'), ('PROD', 'Production'), ('ABANDON', 'Abandoned')], max_length=20)),
                ('step_number', models.IntegerField()),
                ('required_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffing.position')),
            ],
            options={
                'ordering': ['stage', 'step_number'],
                'unique_together': {('stage', 'step_number')},
            },
        ),
    ]
